/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.fourneth

import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new FirstTest(name: 'first')

        when:
        def result = lib.whatsTheDeal()

        then:
        result == 'Deal is first'
    }
}
