pipeline {
    agent 'any'

    stages {
        stage('Is Required To Merge') {
            steps {

            }
        }
        stage('Create PR') {
            steps {

            }
        }
        stage('Run source env testing') {
            steps {

            }
            // if failed, close PR with error
        }
        stage('Wait for necessary PR validations') {
            steps {

            }
        }
        stage('Approve & Merge PR') {
            steps {
                // approve
                // merge
            }
        }
        stage('Create Tab') {

        }
        stage('Deploy') {
            steps {
                // gocd will do this
            }
        }
        stage('Wait for deployment to complete') {

        }
        stage('Run Target Env Testing') {
            steps {

            }
            // if fail revert
        }
        stage('') {

        }
        post {

        }
    }
}